version: '3'

services:
  bob:
    build:
      context: ../
      dockerfile: ./conda_demo/pip/Dockerfile
    volumes:
      - ../conda_demo/pip/:/usr/src/app:consistent
    command: bash
  
  sandy:
    build:
      context: ../
      dockerfile: ./conda_demo/conda/Dockerfile
    volumes:
      - ../conda_demo/conda/:/usr/src/app:consistent
    command: bash